version: 2

project_name: grafana-autodoc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  -
    name: grafana-autodoc
    commit_author:
      name: rastogiji
      email: animesh.rastogi54@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    description: "This package is used to autogenerate markdown files documenting your grafana dashboards as JSON"
    license: "MIT"
    install: |
      bin.install "grafana-autodoc"
    test: |
      system "#{bin}/grafana-autodoc --help"
    repository:
      owner: rastogiji
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"