name: 'Grafana Autodoc'
description: 'Automatically Generate Documentation for your Grafana Dashboards as code.'
author: 'Animesh Rastogi'
inputs:
  dashboard_files:
    description: "file path, directory or glob patterns containing the json representations of your grafana dashboard(s)"
    required: true
  output_dir:
    description: "output directory where to generate the markdown files"
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --input
    - ${{ inputs.dashboard_files }}
    - --output
    - ${{ inputs.output_dir }}

branding:
  icon: 'package'
  color: 'blue'