name: 'Grafana Autodoc'
description: 'Automatically Generate Documentation for your Grafana Dashboards as code.'
author: 'Animesh Rastogi'
inputs:
  dashboard:
    description: "Dashboard's json file path"
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dashboard }}

branding:
  icon: 'package'
  color: 'blue'